name: Validate

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  style:
    name: brew style
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruby syntax check
        run: |
          for f in Formula/*.rb; do ruby -c "$f"; done

      - name: brew style
        run: brew style Formula/*.rb
